[metadata]
hostname = ["127.0.0.1"]

[authentication_placeholder.guard]
hostname = "guard.example.com"

[database.mysql]
username = "example-user"
password_env = "example_user_mysql_password"
hostname = "127.0.0.1"
port = 3306
database = "lighthouse"

[database.s3]
acccess_key_id_env = "s3_access_key_id"
secret_access_key_env = "s3_secret_access_key"
endpoint_url = "https://xxxx.r2.cloudflarestorage.com"
region = "auto"

[smtp]
host="smtp.sendgrid.net"
port=587
username="apikey"
from_alias="Example"
from_header="noreply@paperplane.example.com"
reply_to_address="noreply@paperplane.example.com"
password_env="smtp_password"